version: '3.7'
services:
  postgres:
    image: postgres
    secrets:
      - db_password_new
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_new

  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - postgres

secrets:
  db_password_new:
    external: true
